# Generated by Django 4.2.5 on 2023-10-05 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_products_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_category',
            new_name='category',
        ),
    ]
